from moviepy.editor import *
import random


def vidgen():
    imgs = []
    selectedphotos = []
    clip1 = ImageClip('0.jpg').set_duration(2)
    clip2 = ImageClip('1.jpg').set_duration(2)
    clip3 = ImageClip("2.jpg").set_duration(2)
    clip4 = ImageClip("3.jpg").set_duration(2)
    clip5 = ImageClip('4.jpg').set_duration(2)
    clip6 = ImageClip('5.jpg').set_duration(2)
    clip7 = ImageClip("6.jpg").set_duration(2)
    clip9 = ImageClip("8.jpg").set_duration(2)
    clip10 = ImageClip("9.jpg").set_duration(2)
    clip11 = ImageClip('10.jpg').set_duration(2)
    clip12 = ImageClip('11.jpg').set_duration(2)
    clip13 = ImageClip("12.jpg").set_duration(2)
    clip14 = ImageClip("13.jpg").set_duration(2)
    clip15 = ImageClip('14.jpg').set_duration(2)
    clip17 = ImageClip("16.jpg").set_duration(2)
    clip18 = ImageClip("17.jpg").set_duration(2)
    clip19 = ImageClip("18.jpg").set_duration(2)
    clip20 = ImageClip("19.jpg").set_duration(2)
    clip21 = ImageClip('20.jpg').set_duration(2)
    clip22 = ImageClip('21.jpg').set_duration(2)
    clip23 = ImageClip("22.jpg").set_duration(2)
    clip25 = ImageClip('24.jpg').set_duration(2)
    clip26 = ImageClip('25.jpg').set_duration(2)
    clip27 = ImageClip("26.jpg").set_duration(2)
    clip28 = ImageClip("27.jpg").set_duration(2)
    clip29 = ImageClip("28.jpg").set_duration(2)
    clip30 = ImageClip("29.jpg").set_duration(2)
    imgs.append(clip1)
    imgs.append(clip2)
    imgs.append(clip3)
    imgs.append(clip4)
    imgs.append(clip5)
    imgs.append(clip6)
    imgs.append(clip7)
    imgs.append(clip9)
    imgs.append(clip10)
    imgs.append(clip11)
    imgs.append(clip12)
    imgs.append(clip13)
    imgs.append(clip14)
    imgs.append(clip15)
    imgs.append(clip17)
    imgs.append(clip18)
    imgs.append(clip19)
    imgs.append(clip20)
    imgs.append(clip21)
    imgs.append(clip22)
    imgs.append(clip23)
    imgs.append(clip25)
    imgs.append(clip26)
    imgs.append(clip27)
    imgs.append(clip28)
    imgs.append(clip29)
    imgs.append(clip30)
    for _ in range(7):
        rand = random.randint(0, 26)
        selectedphotos.append(imgs[rand])

    video_clip = concatenate_videoclips(selectedphotos, method='compose')
    video_clip.write_videofile('vid1.mp4', fps=24, codec="libx264", audio_codec="aac")


vidgen()
